import { Link, useParams } from "@tanstack/react-router";
import { Archive, ArrowLeft, PauseCircle, PlayCircle, RefreshCw } from "lucide-react";

import { ErrorState, HealthRing, LoadingState, PageHeader, StatusBadge } from "@/components/shared";
import { Avatar, Button, Card, CardContent, CardHeader } from "@/components/ui";
import { useArchiveEmployee, useEmployee, usePauseEmployee, useResumeEmployee } from "@/hooks";
import type { Employee } from "@/types";
import { formatRelativeTime } from "@/utils/date";

import { useEmployeeHealth } from "../hooks/useEmployeeHealth";
import { getEmployeePerformanceSummary } from "../utils/employeeFilters";

export function EmployeeWorkspacePage() {
  const { employeeId } = useParams({ strict: false });
  const employeeQuery = useEmployee(employeeId ?? "");
  const pauseEmployee = usePauseEmployee();
  const resumeEmployee = useResumeEmployee();
  const archiveEmployee = useArchiveEmployee();
  const employee = employeeQuery.data;
  const health = useEmployeeHealth(employee);

  if (employeeQuery.isLoading) return <LoadingState label="Loading Employee Workspace" />;

  if (employeeQuery.isError || !employee || !health) {
    return (
      <ErrorState
        title="Employee Workspace could not be loaded"
        description="The selected AI Employee was not available. Retry or return to the directory."
        onRetry={() => void employeeQuery.refetch()}
      />
    );
  }

  const performance = getEmployeePerformanceSummary(employee);

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Employee Workspace"
        title={employee.name}
        description={`${employee.role} in ${employee.department}. Current campaign: ${employee.currentCampaign ?? "Available for assignment"}.`}
        actions={
          <>
            <Link
              to="/app/employees"
              className="inline-flex h-11 items-center justify-center gap-2 rounded-[12px] border border-[var(--border)] px-4 text-sm font-semibold hover:bg-[var(--surface-elevated)]"
            >
              <ArrowLeft className="h-4 w-4" aria-hidden="true" />
              Directory
            </Link>
            <WorkspaceActions employee={employee} onPause={() => pauseEmployee.mutate(employee.id)} onResume={() => resumeEmployee.mutate(employee.id)} onArchive={() => archiveEmployee.mutate(employee.id)} />
          </>
        }
      />

      <section className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
        <Card>
          <CardHeader title="Identity" description="Digital employee profile and current assignment." />
          <CardContent>
            <div className="flex items-start gap-4">
              <Avatar name={employee.name} className="h-16 w-16" />
              <div>
                <h2 className="font-display text-2xl font-semibold">{employee.name}</h2>
                <p className="mt-1 text-sm text-[var(--text-secondary)]">{employee.role}</p>
                <div className="mt-3">
                  <StatusBadge status={employee.status} />
                </div>
              </div>
            </div>
            <dl className="mt-6 grid gap-3 text-sm">
              <Info label="Department" value={employee.department} />
              <Info label="Voice" value={employee.voice} />
              <Info label="Language" value={employee.language} />
              <Info label="Knowledge Version" value={`${employee.knowledgeScore}% readiness`} />
              <Info label="Last Active" value={formatRelativeTime(employee.lastActive)} />
            </dl>
          </CardContent>
        </Card>

        <Card>
          <CardHeader title="Performance Summary" description="Business outcomes generated by this AI Employee." />
          <CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <Metric label="Calls Today" value={String(performance.callsToday)} />
            <Metric label="Calls This Month" value={String(performance.callsThisMonth)} />
            <Metric label="Appointments" value={String(performance.appointments)} />
            <Metric label="Average Duration" value={performance.averageDuration} />
            <Metric label="Success Rate" value={`${performance.successRate}%`} />
            <Metric label="Customer Satisfaction" value={`${performance.customerSatisfaction}%`} />
            <Metric label="Revenue Influenced" value={performance.revenueInfluenced} />
            <Metric label="Current Campaign" value={employee.currentCampaign ?? "Available"} />
          </CardContent>
        </Card>
      </section>

      <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
        <Card>
          <CardHeader title="Health Score" description={health.trend} />
          <CardContent>
            <HealthRing value={health.overall} />
            <div className="mt-6 space-y-4">
              <Progress label="Knowledge" value={health.knowledge} />
              <Progress label="Voice" value={health.voice} />
              <Progress label="Conversation Quality" value={health.conversationQuality} />
              <Progress label="Policy Compliance" value={health.policyCompliance} />
              <Progress label="Tool Connectivity" value={health.toolConnectivity} />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader title="Workspace Actions" description="Manage this employee without leaving the workspace." />
          <CardContent className="grid gap-3 md:grid-cols-2">
            <Action title="Retrain Employee" description="Refresh training with the latest knowledge." icon={RefreshCw} />
            <Action title="Assign Campaign" description="Move this employee onto a business objective." icon={PlayCircle} />
            <Action title="Edit Profile" description="Update role, voice, language and responsibilities." icon={RefreshCw} />
            <Action title="Review Analytics" description="Inspect performance, health and customer outcomes." icon={PlayCircle} />
          </CardContent>
        </Card>
      </section>
    </div>
  );
}

function WorkspaceActions({ employee, onPause, onResume, onArchive }: { employee: Employee; onPause: () => void; onResume: () => void; onArchive: () => void }) {
  return (
    <>
      {employee.status === "paused" ? (
        <Button variant="secondary" type="button" onClick={onResume}>
          <PlayCircle className="h-4 w-4" aria-hidden="true" />
          Resume Employee
        </Button>
      ) : (
        <Button variant="secondary" type="button" onClick={onPause}>
          <PauseCircle className="h-4 w-4" aria-hidden="true" />
          Pause Employee
        </Button>
      )}
      <Button variant="danger" type="button" onClick={onArchive}>
        <Archive className="h-4 w-4" aria-hidden="true" />
        Archive
      </Button>
    </>
  );
}

function Info({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-[12px] bg-[var(--surface-elevated)] p-3">
      <dt className="text-[var(--text-secondary)]">{label}</dt>
      <dd className="text-right font-semibold">{value}</dd>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-[16px] bg-[var(--surface-elevated)] p-4">
      <p className="text-xs font-semibold uppercase tracking-normal text-[var(--text-muted)]">{label}</p>
      <p className="mt-2 font-display text-xl font-semibold">{value}</p>
    </div>
  );
}

function Progress({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <div className="flex items-center justify-between text-sm">
        <span className="font-medium">{label}</span>
        <span className="font-semibold">{value}%</span>
      </div>
      <div className="mt-2 h-2 rounded-full bg-[var(--border)]">
        <div className="h-2 rounded-full bg-[var(--ai-accent)]" style={{ width: `${value}%` }} />
      </div>
    </div>
  );
}

function Action({ title, description, icon: Icon }: { title: string; description: string; icon: typeof RefreshCw }) {
  return (
    <button type="button" className="rounded-[16px] border border-[var(--border)] bg-[var(--surface-elevated)] p-4 text-left transition hover:-translate-y-0.5 hover:shadow-sm">
      <Icon className="h-5 w-5 text-[var(--ai-accent)]" aria-hidden="true" />
      <span className="mt-3 block text-sm font-semibold">{title}</span>
      <span className="mt-1 block text-sm leading-6 text-[var(--text-secondary)]">{description}</span>
    </button>
  );
}
